--
-- PostgreSQL database dump
--

-- Dumped from database version 17.4
-- Dumped by pg_dump version 17.4

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: AdditionalMaterials; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."AdditionalMaterials" (
    "AdditionalMaterialId" integer NOT NULL,
    "UriAbsolutePath" character varying(500) NOT NULL,
    "UserId" integer NOT NULL,
    "PostId" integer
);


ALTER TABLE public."AdditionalMaterials" OWNER TO postgres;

--
-- Name: AddtionalMaterials_AddtionalMaterialId_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."AdditionalMaterials" ALTER COLUMN "AdditionalMaterialId" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."AddtionalMaterials_AddtionalMaterialId_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: AuthorizationDatas; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."AuthorizationDatas" (
    "AuthorizationDataId" integer NOT NULL,
    "Login" text NOT NULL,
    "Password" text NOT NULL
);


ALTER TABLE public."AuthorizationDatas" OWNER TO postgres;

--
-- Name: AuthorizationDatas_AuthorizationDataId_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."AuthorizationDatas" ALTER COLUMN "AuthorizationDataId" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."AuthorizationDatas_AuthorizationDataId_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Comments; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Comments" (
    "CommentId" integer NOT NULL,
    "AuthorId" integer NOT NULL,
    "PostId" integer NOT NULL,
    "CommentText" text DEFAULT ''::text NOT NULL,
    "Date" timestamp with time zone DEFAULT '-infinity'::timestamp with time zone NOT NULL
);


ALTER TABLE public."Comments" OWNER TO postgres;

--
-- Name: Comments_CommentId_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Comments" ALTER COLUMN "CommentId" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Comments_CommentId_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: CourseModelStudentModel; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."CourseModelStudentModel" (
    "CoursesCourseId" integer NOT NULL,
    "StudentsUserId" integer NOT NULL
);


ALTER TABLE public."CourseModelStudentModel" OWNER TO postgres;

--
-- Name: Courses; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Courses" (
    "CourseId" integer NOT NULL,
    "GroupId" integer NOT NULL,
    "SubjectId" integer NOT NULL,
    "TeacherId" integer NOT NULL,
    "GroupModelGroupId" integer,
    "SubjectModelSubjectId" integer,
    "TeacherModelUserId" integer
);


ALTER TABLE public."Courses" OWNER TO postgres;

--
-- Name: Courses_CourseId_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Courses" ALTER COLUMN "CourseId" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Courses_CourseId_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Groups; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Groups" (
    "GroupId" integer NOT NULL,
    "CourseNumber" integer NOT NULL,
    "GroupName" text DEFAULT ''::text NOT NULL
);


ALTER TABLE public."Groups" OWNER TO postgres;

--
-- Name: Groups_GroupId_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Groups" ALTER COLUMN "GroupId" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Groups_GroupId_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Housings; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Housings" (
    "HousingId" integer NOT NULL,
    "HousingName" text NOT NULL,
    "HousingAddress" text NOT NULL
);


ALTER TABLE public."Housings" OWNER TO postgres;

--
-- Name: Housings_HousingId_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Housings" ALTER COLUMN "HousingId" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Housings_HousingId_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: LessonSlots; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."LessonSlots" (
    "LessonSlotId" integer NOT NULL,
    "LessonStart" time without time zone NOT NULL,
    "LessonEnd" time without time zone NOT NULL
);


ALTER TABLE public."LessonSlots" OWNER TO postgres;

--
-- Name: LessonSlotModel_LessonSlotId_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."LessonSlots" ALTER COLUMN "LessonSlotId" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."LessonSlotModel_LessonSlotId_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: LessonSupressedRequests; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."LessonSupressedRequests" (
    "SupersedeRequestId" integer NOT NULL,
    "TeacherId" integer NOT NULL,
    "DateToSupersede" date NOT NULL,
    "LessonSlotId" integer NOT NULL,
    "SubjectId" integer NOT NULL,
    "RequestTime" timestamp with time zone NOT NULL,
    "GroupId" integer DEFAULT 0 NOT NULL,
    "SupersedeRequestStatus" integer DEFAULT 0 NOT NULL,
    "SupersedeRequestType" integer DEFAULT 0 NOT NULL,
    "AffectedLessonId" integer
);


ALTER TABLE public."LessonSupressedRequests" OWNER TO postgres;

--
-- Name: LessonSupressedRequests_SupersedeRequestId_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."LessonSupressedRequests" ALTER COLUMN "SupersedeRequestId" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."LessonSupressedRequests_SupersedeRequestId_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Lessons; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Lessons" (
    "LessonId" integer NOT NULL,
    "SubjectId" integer NOT NULL,
    "GroupId" integer NOT NULL,
    "TeacherId" integer NOT NULL,
    "DayOfWeek" integer NOT NULL,
    "WeekType" integer NOT NULL,
    "LessonNumberId" integer NOT NULL,
    "HousingId" integer NOT NULL
);


ALTER TABLE public."Lessons" OWNER TO postgres;

--
-- Name: Lessons_LessonId_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Lessons" ALTER COLUMN "LessonId" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Lessons_LessonId_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: PersonalDatas; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."PersonalDatas" (
    "PersonalDataId" integer NOT NULL,
    "Name" text NOT NULL,
    "Lastname" text NOT NULL,
    "Patronymic" text,
    "PhoneNumber" text NOT NULL,
    "Email" text DEFAULT 'Не установлена'::text NOT NULL,
    "AvatarAbsoluteUri" text
);


ALTER TABLE public."PersonalDatas" OWNER TO postgres;

--
-- Name: PersonalDatas_PersonalDataId_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."PersonalDatas" ALTER COLUMN "PersonalDataId" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."PersonalDatas_PersonalDataId_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: PostThemes; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."PostThemes" (
    "PostThemeId" integer NOT NULL,
    "PostThemeText" text NOT NULL,
    "CourseId" integer DEFAULT 0 NOT NULL
);


ALTER TABLE public."PostThemes" OWNER TO postgres;

--
-- Name: PostThemes_PostThemeId_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."PostThemes" ALTER COLUMN "PostThemeId" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."PostThemes_PostThemeId_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Posts; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Posts" (
    "PostId" integer NOT NULL,
    "PostTitle" text NOT NULL,
    "PostDescription" text NOT NULL,
    "PostType" integer NOT NULL,
    "PostThemeId" integer NOT NULL,
    "CourseId" integer NOT NULL,
    "UserId" integer NOT NULL,
    "AdministratorModelUserId" integer,
    "StudentModelUserId" integer,
    "Created" timestamp with time zone DEFAULT '-infinity'::timestamp with time zone NOT NULL
);


ALTER TABLE public."Posts" OWNER TO postgres;

--
-- Name: Posts_PostId_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Posts" ALTER COLUMN "PostId" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Posts_PostId_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: RefreshTokens; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."RefreshTokens" (
    "RefreshTokenId" integer NOT NULL,
    "UserId" integer NOT NULL,
    "Token" text NOT NULL,
    "ExpirationDate" timestamp with time zone NOT NULL,
    "IsRevoked" boolean DEFAULT false NOT NULL
);


ALTER TABLE public."RefreshTokens" OWNER TO postgres;

--
-- Name: RefreshTokens_RefreshTokenId_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."RefreshTokens" ALTER COLUMN "RefreshTokenId" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."RefreshTokens_RefreshTokenId_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Subjects; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Subjects" (
    "SubjectId" integer NOT NULL,
    "SubjectName" text NOT NULL,
    "HexademicalColor" character varying(500) DEFAULT ''::character varying NOT NULL
);


ALTER TABLE public."Subjects" OWNER TO postgres;

--
-- Name: Subjects_SubjectId_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Subjects" ALTER COLUMN "SubjectId" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Subjects_SubjectId_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: SurveyAnswers; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."SurveyAnswers" (
    "SurveyOptionId" integer NOT NULL,
    "SurveyAnswerId" integer NOT NULL,
    "StudentId" integer NOT NULL,
    "PostId" integer NOT NULL,
    "CommitTime" timestamp with time zone NOT NULL
);


ALTER TABLE public."SurveyAnswers" OWNER TO postgres;

--
-- Name: SurveyAnswers_SurveyAnswerId_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."SurveyAnswers" ALTER COLUMN "SurveyAnswerId" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."SurveyAnswers_SurveyAnswerId_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: SurveyOptions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."SurveyOptions" (
    "SurveyOptionId" integer NOT NULL,
    "PostId" integer NOT NULL,
    "OptionName" text NOT NULL
);


ALTER TABLE public."SurveyOptions" OWNER TO postgres;

--
-- Name: SurveyOptions_SurveyOptionId_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."SurveyOptions" ALTER COLUMN "SurveyOptionId" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."SurveyOptions_SurveyOptionId_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: TaskAnswers; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."TaskAnswers" (
    "TaskAnswerId" integer NOT NULL,
    "AdditionalMaterialId" integer,
    "StudentId" integer NOT NULL,
    "TaskId" integer NOT NULL,
    "AssignmentTime" timestamp with time zone DEFAULT '-infinity'::timestamp with time zone NOT NULL
);


ALTER TABLE public."TaskAnswers" OWNER TO postgres;

--
-- Name: TaskAnswers_TaskAnswerId_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."TaskAnswers" ALTER COLUMN "TaskAnswerId" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."TaskAnswers_TaskAnswerId_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Tasks; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Tasks" (
    "PostId" integer NOT NULL,
    "DueTime" timestamp with time zone NOT NULL,
    "SubjectId" integer NOT NULL,
    "TeacherId" integer NOT NULL,
    "CourseId" integer NOT NULL,
    "TaskStatusEnum" integer NOT NULL,
    "StudentId" integer NOT NULL,
    "MaxMark" integer NOT NULL,
    "Mark" integer,
    "LastUpdate" timestamp with time zone DEFAULT '-infinity'::timestamp with time zone NOT NULL,
    "TaskId" integer NOT NULL
);


ALTER TABLE public."Tasks" OWNER TO postgres;

--
-- Name: Tasks_TaskId_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Tasks" ALTER COLUMN "TaskId" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Tasks_TaskId_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Users" (
    "UserId" integer NOT NULL,
    "PersonalDataId" integer NOT NULL,
    "AuthorizationDataId" integer NOT NULL,
    "UserType" character varying(13) NOT NULL,
    "GroupId" integer
);


ALTER TABLE public."Users" OWNER TO postgres;

--
-- Name: Users_UserId_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Users" ALTER COLUMN "UserId" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Users_UserId_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


ALTER TABLE public."__EFMigrationsHistory" OWNER TO postgres;

--
-- Data for Name: AdditionalMaterials; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."AdditionalMaterials" ("AdditionalMaterialId", "UriAbsolutePath", "UserId", "PostId") FROM stdin;
20	D:\\mptroomfiles\\Fourth\\P50-6-21\\OKFKS\\StartsevKS\\file.png	4	10
21	D:\\mptroomfiles\\Fourth\\P50-6-21\\OKFKS\\StartsevKS\\photo_2025-04-05_19-18-46.jpg	4	10
22	D:\\mptroomfiles\\Fourth\\P50-6-21\\OKFKS\\StartsevKS\\e152b02504ce97b9fb47a9d87de73141.jpg	4	10
23	D:\\mptroomfiles\\Fourth\\P50-6-21\\OKFKS\\МКА_Python(Junior)_ДЗ_10_2022.pdf	18	16
24	D:\\mptroomfiles\\Fourth\\P50-6-21\\OKFKS\\П50-6-21 Старцев К. С..pptx	18	16
28	D:\\mptroomfiles\\Fourth\\P50-6-21\\Vnedrenie_i_podderzhka_KS\\StartsevKS\\0730193357050e6dd0e369c876b9f60e.jpg	4	31
29	D:\\mptroomfiles\\Fourth\\P50-6-21\\Ekonomika_otrasli\\StartsevKS\\e6ea629077e1777bf89b140af1ad3e69.jpg	4	32
\.


--
-- Data for Name: AuthorizationDatas; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."AuthorizationDatas" ("AuthorizationDataId", "Login", "Password") FROM stdin;
3	admin	$2a$11$eJ1pJNMaZzeAIhd.nUgPmOUAmaoO0WlCstDe9JAZ1c086HUXE0DWa
6	vawenetut	$2a$11$eC9xJCk3pwB1dP6KRtT1HO7gGR6niuysJyW7rJMntAQUkJm6kRaWu
7	vawenetut	$2a$11$6lK5Gf8j1B2AY9ujD2z2R.2dN4RtgyAeBMD2HXGDepS/cDdIgA/Y2
8	vawenetut	$2a$11$z9kkMPaeRfvTvzCgzKUT9eih5RvFHNdrr/8m6wfOTiQwGV8nbzx8q
9	vawenetut	$2a$11$qseCquqWD.ZUJm9vQQBZyeYifaJ/JBKM2OCtDydTxtuhjvD2soiNy
10	vawenetut	$2a$11$d0mhxFhKmuc0MbbmRhhZxe5tnsQJ8lul0CMZv4gGK7lma8xmS5u6i
11	vawenetut	$2a$11$PXq.7F3X9s8K45nhinwCVurKhClaii.BTz0fWusn0/X8P.MiepfF2
12	onsch	$2a$11$aFDei2ZECICjLhji5iIdSe5om6Q5eCvv1pxusLI1DsQpqc50gIKMK
13	armia	$2a$11$M8qPfuekE60yYySqX46NZuivVT3KucMtxHtQhjFZF3HE/fX/1mabq
16	gorbunov	$2a$11$bDTASgC5gTGXFEQWDQ1RT.INsF2Y7Jyw.j1UKTGgX3s7pJVz4PxlG
17	english	$2a$11$i7CnllI8I8LGaSfYQoaeEe/heuEQSmbr0iIkGIuWn3b/g1mvcTMqS
18	malo	$2a$11$XFLouBv8PuWh93PhFIztn.ZjJFPZa5fPNgyMecQc0IGLbp/oDeHfK
19	ivanov	$2a$11$kh4X1yzVD91wtXGkphDVhOz4rc9nP09P3ukENx4NfrrqYnCUQGwiO
20	ivanon	$2a$11$aWfi1dBNDdnGxVLp9A8SJ.uL1LadU.5jkAK.o9pgxqR/Hlcwcqpm6
21	xvxMAxvx	$2a$11$2siwp14MFqDY8WGIiqC6YeMfAFMjsSiHYm6mkXcaIqiv.zhCgdjF2
22	ivanov	$2a$11$4yCov6jTisHEwrlGvUsZM.KS/GUaHV.ezdqxag9imaC9/NgaZ2lT2
23	ivanov	$2a$11$42FGm2WslA9RxIGKMYAMUOS/YgfccHtvhKaZMmkVDzyeuhGDukYfK
24	xvxMAxvx	$2a$11$uS.NCxUumwoaDDPSiIiabuwirwnwQNHXEZzs2814tkbaesQ1od4R.
5	JulikNeVoryi	$2a$11$4BVvH9XRm9dI0XQy/bqA7Ohx3encGGiwwVOQNrgDZk72jqWzacUYi
14	unluck	$2a$11$OCb2Etpl51CyDzGWywJRpuakwB7w6bHFyighDB4fuveUgDc0eDeJ6
15	docker	$2a$11$E8MNXMQ4t1arTTzKEkVLvuwtYfMW9O3.vUDOfzSU6U1DSycXof2Vu
4	ker1xx	$2a$11$GDtzmCJ3uZSms4dfTZdwvOXL2lF1GoXJi6GEio9o2jlVav4VkNdAW
25	bam	$2a$11$TZvt82V904CC3CC8BltFTONxZrVF5.9cuSWGSmKR..hR.6eDDlNYy
26	sercetBotLogin	$2a$11$5a1fYWNPspDD6y7RCfXbD.JYvS7UgCdWkWa03Vf2JmVU.XQIHH6Am
\.


--
-- Data for Name: Comments; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Comments" ("CommentId", "AuthorId", "PostId", "CommentText", "Date") FROM stdin;
2	5	31	Всем все понятно????	2025-05-09 23:35:34.217462+03
\.


--
-- Data for Name: CourseModelStudentModel; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."CourseModelStudentModel" ("CoursesCourseId", "StudentsUserId") FROM stdin;
\.


--
-- Data for Name: Courses; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Courses" ("CourseId", "GroupId", "SubjectId", "TeacherId", "GroupModelGroupId", "SubjectModelSubjectId", "TeacherModelUserId") FROM stdin;
4	1	4	15	\N	\N	\N
5	1	5	16	\N	\N	\N
8	1	6	17	\N	\N	\N
9	1	7	20	\N	\N	\N
3	1	3	21	\N	\N	\N
7	1	2	19	\N	\N	\N
2	1	2	18	\N	\N	\N
12	8	11	27	\N	\N	\N
1	1	1	5	\N	\N	\N
\.


--
-- Data for Name: Groups; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Groups" ("GroupId", "CourseNumber", "GroupName") FROM stdin;
1	4	П50-6-21
2	4	П50-7-21
8	4	П50-8-21
\.


--
-- Data for Name: Housings; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Housings" ("HousingId", "HousingName", "HousingAddress") FROM stdin;
1	Нахимовский	Нахимовский проспект, д. 21, Москва, Россия, 117149
2	Нежинская	Нежинская улица, д. 7, Москва, Россия, 119501
\.


--
-- Data for Name: LessonSlots; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."LessonSlots" ("LessonSlotId", "LessonStart", "LessonEnd") FROM stdin;
1	08:30:00	10:00:00
2	10:10:00	11:40:00
3	12:00:00	13:30:00
4	13:50:00	15:20:00
5	15:30:00	17:00:00
\.


--
-- Data for Name: LessonSupressedRequests; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."LessonSupressedRequests" ("SupersedeRequestId", "TeacherId", "DateToSupersede", "LessonSlotId", "SubjectId", "RequestTime", "GroupId", "SupersedeRequestStatus", "SupersedeRequestType", "AffectedLessonId") FROM stdin;
21	5	2025-05-12	1	1	2025-05-12 22:06:28.947+03	1	2	1	4
22	5	2025-05-13	3	1	2025-05-13 00:37:08.42+03	1	1	3	\N
8	17	2025-05-12	5	6	2025-05-11 11:37:05.985+03	1	2	3	\N
\.


--
-- Data for Name: Lessons; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Lessons" ("LessonId", "SubjectId", "GroupId", "TeacherId", "DayOfWeek", "WeekType", "LessonNumberId", "HousingId") FROM stdin;
4	1	1	5	1	0	4	1
10	2	1	19	1	0	2	1
11	4	1	15	1	1	3	1
14	3	1	21	1	2	3	1
15	1	2	5	1	0	3	1
16	2	2	19	1	0	1	1
22	2	1	18	1	0	1	1
23	4	1	15	4	0	1	2
24	5	1	16	4	0	2	2
26	3	1	21	5	0	2	1
31	6	1	17	4	0	3	2
27	2	1	18	5	2	3	1
28	1	1	5	5	1	4	1
32	4	1	15	5	1	3	1
25	6	1	17	5	2	1	1
33	7	1	20	5	1	1	1
34	11	8	27	1	1	1	1
35	4	8	15	1	2	1	1
36	11	8	27	3	0	1	2
38	1	1	5	4	0	4	2
\.


--
-- Data for Name: PersonalDatas; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."PersonalDatas" ("PersonalDataId", "Name", "Lastname", "Patronymic", "PhoneNumber", "Email", "AvatarAbsoluteUri") FROM stdin;
1	Иван	Иванов	Иванович	89001112233		\N
2	Кирилл	Старцев	Станиславович	+79104374595	isip_k.s.starcev@mpt.ru	D:\\mptroomfiles\\avatars\\2.jpg
4	Никита	Романов	Михайлович	+79991232233	isip_n.m.romanov@mpt.ru	\N
5	Никита	Романов	Михайлович	+79991232233	isip_n.m.romanov@mpt.ru	\N
6	Никита	Романов	Михайлович	+79991232233	isip_n.m.romanov@mpt.ru	\N
7	Никита	Романов	Михайлович	+79991232233	isip_n.m.romanov@mpt.ru	\N
8	Никита	Романов	Михайлович	+79991232233	isip_n.m.romanov@mpt.ru	\N
9	Никита	Романов	Михайлович	+79991232233	isip_n.m.romanov@mpt.ru	\N
10	Ольга	Шестакова	Николаевна	+79123128233	o.n.shestakova@mpt.ru	\N
11	Ольга	Шестакова	Николаевна	+79123128233	o.n.shestakova@mpt.ru	\N
12	Ольга	Шестакова	Николаевна	+79123128233	o.n.shestakova@mpt.ru	\N
13	Ольга	Шестакова	Николаевна	+79123128233	o.n.shestakova@mpt.ru	\N
14	Андрей	Андрюков	Викторович	+79999999999	a.v.andrykov@mpt.ru	\N
17	Андрей	Горбунов	Дмитриевич	+77777777777	a.d.grobunov@mpt.ru	\N
18	Екатерина	Афанасьева	Валерьевна	+79123215654	e.v.afanaseva@mpt.ru	\N
19	Екатерина	Бойцова	Юрьевна	+70000001122	e.v.boytsova@mpt.ru	\N
20					admin	\N
21					admin	\N
22						\N
23	Иван	Иванов	Иванович	+79999991231	isip_i.i.ivanov@mpt.ru	\N
24	Иван	Иванов	Иванович	+791232322323	isip_i.i.ivanov@mpt.ru	\N
25	Мария	Горбунова	Александровна	+71111111111	isip_m.a.gorbunova@mpt.ru	\N
26	Иван	Иванов	Иванович	+79823232323	isip_i.i.ivanov@mpt.ru	\N
27	Иван	Иванов	Иванович	+7923232323	isip_i.i.ivanov@mpt.ru	\N
28	Мария	Горбунова	Александровна	+71112345678	isip_m.a.gorbunova@mpt.ru	\N
15	Любовь	Попова	Юрьевна	+71231231122	l.u.popova@mpt.ru	D:\\mptroomfiles\\avatars\\15.jpg
29	бам	бам	бам	+79991231212	dasdasdsadsa@mail.ru	\N
16	Ксения	Образцова	Сергеевна	+70000000000	k.s.obraztsova@mpt.ru	\N
3	Даниил	Серяк	Владимирович	+79991231212	d.v.seryak@mpt.ru	D:\\mptroomfiles\\avatars\\3.jpg
\.


--
-- Data for Name: PostThemes; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."PostThemes" ("PostThemeId", "PostThemeText", "CourseId") FROM stdin;
1	Практическая работа №7	1
2	Практическая работа № 11	2
3	тест задание	2
4	тест пост	1
6	тестирование материала	2
7	Опросики	1
8	Опрос как дела	1
9	Практическая 11	1
10	Практическая 11	8
11	Практическая 10	1
12	Практическая № 5	8
\.


--
-- Data for Name: Posts; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Posts" ("PostId", "PostTitle", "PostDescription", "PostType", "PostThemeId", "CourseId", "UserId", "AdministratorModelUserId", "StudentModelUserId", "Created") FROM stdin;
10	тест задание	тест задание описание 	3	3	2	18	\N	\N	2025-04-30 14:33:04.733+03
16	тест материала	Тестирование дополнительного материала но вы все равно посмотрите внимательно!!	1	6	2	18	\N	\N	2025-05-02 04:16:07.151+03
17	ВАЖНЫЙ ОПРОС	Как у вас делишки?)))))	2	8	1	5	\N	\N	2025-05-02 05:21:24.281+03
20	Круто или нет	круто?	2	2	2	18	\N	\N	2025-05-02 07:13:06.724+03
28	Практическая работа № 11	описано задание практической работы	3	10	8	17	\N	\N	2025-05-07 21:07:13.492+03
31	Практическая работа № 10	описание задания практоса 10	3	11	1	5	\N	\N	2025-05-09 06:34:35.927+03
32	Практическая работа № 5	практос	3	12	8	17	\N	\N	2025-05-11 11:48:09.719+03
7	тест пост имя	тест пост	0	4	1	5	\N	\N	2025-04-24 19:25:05.955+03
\.


--
-- Data for Name: RefreshTokens; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."RefreshTokens" ("RefreshTokenId", "UserId", "Token", "ExpirationDate", "IsRevoked") FROM stdin;
17	28	udyFL/9UvFdXGHxaBdYQ6jnpv52dCMOrMosS0J3UHqc=	2026-05-11 23:35:43.140547+03	f
11	18	QZZ7aP/qo7LxWJqESzoG/X34ld/r9vZvq4xsQp0zjDs=	2026-05-11 23:36:23.039612+03	f
15	5	bKBUuweNVBOYtn6MKhoqq+bGLsSaYQFKha6c99eCPxo=	2026-05-13 00:38:07.707574+03	f
13	4	V//hnNUpqtb7G/q/kNgoNH2G6LTyyPtunl1wCq6YNfg=	2026-05-13 00:43:31.466042+03	f
14	3	YT40heR8gytTdoquoDrLWp/ESlVotFkfmA3aut5jkDw=	2026-05-13 00:44:01.138386+03	f
16	17	RKFI6c2tLDa0sR1Rn+p3WZ+9Z2csmQzbq/eUIe18V/g=	2026-05-11 11:19:58.562579+03	f
\.


--
-- Data for Name: Subjects; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Subjects" ("SubjectId", "SubjectName", "HexademicalColor") FROM stdin;
1	Внедрение и поддержка КС	#4965F2
2	ОКФКС	#fe39c9
3	ТРПО	#e4ce3f
4	Математическое моделирование	#e37f0d
5	Физическая культура	#3dd629
6	Экономика отрасли	#960bb1
7	Английский язык в ПД	#15bec1
11	МДК 01.02 Поддержка и тестирование программных модулей	#ab2121
\.


--
-- Data for Name: SurveyAnswers; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."SurveyAnswers" ("SurveyOptionId", "SurveyAnswerId", "StudentId", "PostId", "CommitTime") FROM stdin;
1	2	4	17	2025-05-02 06:57:06.39+03
7	3	4	20	2025-05-02 07:13:16.181+03
\.


--
-- Data for Name: SurveyOptions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."SurveyOptions" ("SurveyOptionId", "PostId", "OptionName") FROM stdin;
1	17	Супер!
3	17	Неоч(
2	17	Пойдет...
6	20	круто
7	20	не круто
\.


--
-- Data for Name: TaskAnswers; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."TaskAnswers" ("TaskAnswerId", "AdditionalMaterialId", "StudentId", "TaskId", "AssignmentTime") FROM stdin;
8	28	4	15	2025-05-09 07:20:57.865169+03
9	29	4	17	2025-05-11 11:49:19.665795+03
\.


--
-- Data for Name: Tasks; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Tasks" ("PostId", "DueTime", "SubjectId", "TeacherId", "CourseId", "TaskStatusEnum", "StudentId", "MaxMark", "Mark", "LastUpdate", "TaskId") FROM stdin;
28	2025-05-07 21:12:00+03	6	17	8	4	4	5	\N	2025-05-07 21:07:13.579+03	7
28	2025-05-07 21:12:00+03	6	17	8	4	11	5	\N	2025-05-07 21:07:13.579+03	8
31	2025-05-09 07:25:00+03	1	5	1	4	11	5	\N	2025-05-09 07:20:35.231+03	16
31	2025-05-09 07:25:00+03	1	5	1	3	4	5	5	2025-05-09 07:20:35.231+03	15
32	2025-05-11 12:00:00+03	6	17	8	3	4	5	5	2025-05-11 11:48:09.77+03	17
32	2025-05-11 12:00:00+03	6	17	8	4	11	5	\N	2025-05-11 11:48:09.77+03	18
\.


--
-- Data for Name: Users; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Users" ("UserId", "PersonalDataId", "AuthorizationDataId", "UserType", "GroupId") FROM stdin;
3	1	3	Administrator	\N
5	3	5	Teacher	\N
11	9	11	Student	1
15	13	12	Teacher	\N
16	14	13	Teacher	\N
17	15	14	Teacher	\N
19	17	16	Teacher	\N
20	18	17	Teacher	\N
21	19	18	Teacher	\N
4	2	4	Student	1
27	28	24	Teacher	\N
18	16	15	Teacher	\N
28	29	25	Student	2
\.


--
-- Data for Name: __EFMigrationsHistory; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."__EFMigrationsHistory" ("MigrationId", "ProductVersion") FROM stdin;
20250227102107_InitializeDatabase	9.0.2
20250227110312_CreateCourseStudentM2M	9.0.2
20250305064711_AddedGroupNameAndCourseHexColor	9.0.2
20250305231740_RemovedSaltFromAuthData	9.0.2
20250305234739_AddedRefreshToken	9.0.2
20250310223346_AddedEmailToPersonalData	9.0.2
20250331003718_TaskLastUpdateAdd	9.0.2
20250331024659_ChangeHexSubjectColorPlacement	9.0.2
20250410032453_AddPostCreationDate	9.0.2
20250501004905_AddAssignmentTimeOnTaskAnswer	9.0.2
20250501143704_ChangedTaskAnswerAdditionalMaterialTypeToNullable	9.0.2
20250501180352_AddedIsRevokedToRefreshToken	9.0.2
20250501232420_AddSurveyAnswer	9.0.2
20250502002929_AddedCourseIdToPostTheme	9.0.2
20250502003341_ChangedCourseIdInPostTheme	9.0.2
20250502020657_RefactorPostAndTask	9.0.2
20250502032430_FixSurveyAnswerPK	9.0.2
20250504193851_AddedAvatar	9.0.2
20250505194344_AddedCommentsAndLessonSupersedeModels	9.0.2
20250506004150_FixedCommentsAndLessonSupersedeModels	9.0.2
20250506010204_AddedDateToCommentModel	9.0.2
20250506015429_AddedGroupToLessonSupersedeRequestModel	9.0.2
20250506103103_AddedTaskIdToTaskModel	9.0.2
20250506104244_ChangedTaskModelPK	9.0.2
20250506105806_ChangedTaskModelTeacherFKToOneToMany	9.0.2
20250509031012_FixedAMPostLink	9.0.2
20250509031929_FinalFixedAMPostLink	9.0.2
20250510235652_AddedRequestTypeToLessonSupersedeRequest	9.0.2
20250511000858_AddedAffectedLessonToLessonSupersedeRequest	9.0.2
\.


--
-- Name: AddtionalMaterials_AddtionalMaterialId_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."AddtionalMaterials_AddtionalMaterialId_seq"', 29, true);


--
-- Name: AuthorizationDatas_AuthorizationDataId_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."AuthorizationDatas_AuthorizationDataId_seq"', 26, true);


--
-- Name: Comments_CommentId_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Comments_CommentId_seq"', 4, true);


--
-- Name: Courses_CourseId_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Courses_CourseId_seq"', 12, true);


--
-- Name: Groups_GroupId_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Groups_GroupId_seq"', 9, true);


--
-- Name: Housings_HousingId_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Housings_HousingId_seq"', 2, true);


--
-- Name: LessonSlotModel_LessonSlotId_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."LessonSlotModel_LessonSlotId_seq"', 5, true);


--
-- Name: LessonSupressedRequests_SupersedeRequestId_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."LessonSupressedRequests_SupersedeRequestId_seq"', 22, true);


--
-- Name: Lessons_LessonId_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Lessons_LessonId_seq"', 38, true);


--
-- Name: PersonalDatas_PersonalDataId_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."PersonalDatas_PersonalDataId_seq"', 29, true);


--
-- Name: PostThemes_PostThemeId_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."PostThemes_PostThemeId_seq"', 12, true);


--
-- Name: Posts_PostId_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Posts_PostId_seq"', 32, true);


--
-- Name: RefreshTokens_RefreshTokenId_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."RefreshTokens_RefreshTokenId_seq"', 17, true);


--
-- Name: Subjects_SubjectId_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Subjects_SubjectId_seq"', 11, true);


--
-- Name: SurveyAnswers_SurveyAnswerId_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."SurveyAnswers_SurveyAnswerId_seq"', 5, true);


--
-- Name: SurveyOptions_SurveyOptionId_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."SurveyOptions_SurveyOptionId_seq"', 10, true);


--
-- Name: TaskAnswers_TaskAnswerId_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."TaskAnswers_TaskAnswerId_seq"', 9, true);


--
-- Name: Tasks_TaskId_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Tasks_TaskId_seq"', 18, true);


--
-- Name: Users_UserId_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Users_UserId_seq"', 29, true);


--
-- Name: AdditionalMaterials PK_AdditionalMaterials; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AdditionalMaterials"
    ADD CONSTRAINT "PK_AdditionalMaterials" PRIMARY KEY ("AdditionalMaterialId");


--
-- Name: AuthorizationDatas PK_AuthorizationDatas; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AuthorizationDatas"
    ADD CONSTRAINT "PK_AuthorizationDatas" PRIMARY KEY ("AuthorizationDataId");


--
-- Name: Comments PK_Comments; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Comments"
    ADD CONSTRAINT "PK_Comments" PRIMARY KEY ("CommentId");


--
-- Name: CourseModelStudentModel PK_CourseModelStudentModel; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."CourseModelStudentModel"
    ADD CONSTRAINT "PK_CourseModelStudentModel" PRIMARY KEY ("CoursesCourseId", "StudentsUserId");


--
-- Name: Courses PK_Courses; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Courses"
    ADD CONSTRAINT "PK_Courses" PRIMARY KEY ("CourseId");


--
-- Name: Groups PK_Groups; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Groups"
    ADD CONSTRAINT "PK_Groups" PRIMARY KEY ("GroupId");


--
-- Name: Housings PK_Housings; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Housings"
    ADD CONSTRAINT "PK_Housings" PRIMARY KEY ("HousingId");


--
-- Name: LessonSlots PK_LessonSlots; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."LessonSlots"
    ADD CONSTRAINT "PK_LessonSlots" PRIMARY KEY ("LessonSlotId");


--
-- Name: LessonSupressedRequests PK_LessonSupressedRequests; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."LessonSupressedRequests"
    ADD CONSTRAINT "PK_LessonSupressedRequests" PRIMARY KEY ("SupersedeRequestId");


--
-- Name: Lessons PK_Lessons; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Lessons"
    ADD CONSTRAINT "PK_Lessons" PRIMARY KEY ("LessonId");


--
-- Name: PersonalDatas PK_PersonalDatas; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."PersonalDatas"
    ADD CONSTRAINT "PK_PersonalDatas" PRIMARY KEY ("PersonalDataId");


--
-- Name: PostThemes PK_PostThemes; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."PostThemes"
    ADD CONSTRAINT "PK_PostThemes" PRIMARY KEY ("PostThemeId");


--
-- Name: Posts PK_Posts; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Posts"
    ADD CONSTRAINT "PK_Posts" PRIMARY KEY ("PostId");


--
-- Name: RefreshTokens PK_RefreshTokens; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."RefreshTokens"
    ADD CONSTRAINT "PK_RefreshTokens" PRIMARY KEY ("RefreshTokenId");


--
-- Name: Subjects PK_Subjects; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Subjects"
    ADD CONSTRAINT "PK_Subjects" PRIMARY KEY ("SubjectId");


--
-- Name: SurveyAnswers PK_SurveyAnswers; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."SurveyAnswers"
    ADD CONSTRAINT "PK_SurveyAnswers" PRIMARY KEY ("SurveyAnswerId");


--
-- Name: SurveyOptions PK_SurveyOptions; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."SurveyOptions"
    ADD CONSTRAINT "PK_SurveyOptions" PRIMARY KEY ("SurveyOptionId");


--
-- Name: TaskAnswers PK_TaskAnswers; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."TaskAnswers"
    ADD CONSTRAINT "PK_TaskAnswers" PRIMARY KEY ("TaskAnswerId");


--
-- Name: Tasks PK_Tasks; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Tasks"
    ADD CONSTRAINT "PK_Tasks" PRIMARY KEY ("TaskId");


--
-- Name: Users PK_Users; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Users"
    ADD CONSTRAINT "PK_Users" PRIMARY KEY ("UserId");


--
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


--
-- Name: IX_AdditionalMaterials_PostId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_AdditionalMaterials_PostId" ON public."AdditionalMaterials" USING btree ("PostId");


--
-- Name: IX_AdditionalMaterials_UserId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_AdditionalMaterials_UserId" ON public."AdditionalMaterials" USING btree ("UserId");


--
-- Name: IX_Comments_AuthorId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Comments_AuthorId" ON public."Comments" USING btree ("AuthorId");


--
-- Name: IX_Comments_PostId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Comments_PostId" ON public."Comments" USING btree ("PostId");


--
-- Name: IX_CourseModelStudentModel_StudentsUserId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_CourseModelStudentModel_StudentsUserId" ON public."CourseModelStudentModel" USING btree ("StudentsUserId");


--
-- Name: IX_Courses_GroupId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Courses_GroupId" ON public."Courses" USING btree ("GroupId");


--
-- Name: IX_Courses_GroupModelGroupId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Courses_GroupModelGroupId" ON public."Courses" USING btree ("GroupModelGroupId");


--
-- Name: IX_Courses_SubjectId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Courses_SubjectId" ON public."Courses" USING btree ("SubjectId");


--
-- Name: IX_Courses_SubjectModelSubjectId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Courses_SubjectModelSubjectId" ON public."Courses" USING btree ("SubjectModelSubjectId");


--
-- Name: IX_Courses_TeacherId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Courses_TeacherId" ON public."Courses" USING btree ("TeacherId");


--
-- Name: IX_Courses_TeacherModelUserId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Courses_TeacherModelUserId" ON public."Courses" USING btree ("TeacherModelUserId");


--
-- Name: IX_LessonSupressedRequests_AffectedLessonId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_LessonSupressedRequests_AffectedLessonId" ON public."LessonSupressedRequests" USING btree ("AffectedLessonId");


--
-- Name: IX_LessonSupressedRequests_GroupId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_LessonSupressedRequests_GroupId" ON public."LessonSupressedRequests" USING btree ("GroupId");


--
-- Name: IX_LessonSupressedRequests_LessonSlotId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_LessonSupressedRequests_LessonSlotId" ON public."LessonSupressedRequests" USING btree ("LessonSlotId");


--
-- Name: IX_LessonSupressedRequests_SubjectId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_LessonSupressedRequests_SubjectId" ON public."LessonSupressedRequests" USING btree ("SubjectId");


--
-- Name: IX_LessonSupressedRequests_TeacherId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_LessonSupressedRequests_TeacherId" ON public."LessonSupressedRequests" USING btree ("TeacherId");


--
-- Name: IX_Lessons_GroupId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Lessons_GroupId" ON public."Lessons" USING btree ("GroupId");


--
-- Name: IX_Lessons_HousingId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Lessons_HousingId" ON public."Lessons" USING btree ("HousingId");


--
-- Name: IX_Lessons_LessonNumberId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Lessons_LessonNumberId" ON public."Lessons" USING btree ("LessonNumberId");


--
-- Name: IX_Lessons_SubjectId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Lessons_SubjectId" ON public."Lessons" USING btree ("SubjectId");


--
-- Name: IX_Lessons_TeacherId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Lessons_TeacherId" ON public."Lessons" USING btree ("TeacherId");


--
-- Name: IX_PostThemes_CourseId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_PostThemes_CourseId" ON public."PostThemes" USING btree ("CourseId");


--
-- Name: IX_Posts_AdministratorModelUserId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Posts_AdministratorModelUserId" ON public."Posts" USING btree ("AdministratorModelUserId");


--
-- Name: IX_Posts_CourseId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Posts_CourseId" ON public."Posts" USING btree ("CourseId");


--
-- Name: IX_Posts_PostThemeId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Posts_PostThemeId" ON public."Posts" USING btree ("PostThemeId");


--
-- Name: IX_Posts_StudentModelUserId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Posts_StudentModelUserId" ON public."Posts" USING btree ("StudentModelUserId");


--
-- Name: IX_Posts_UserId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Posts_UserId" ON public."Posts" USING btree ("UserId");


--
-- Name: IX_RefreshTokens_UserId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX "IX_RefreshTokens_UserId" ON public."RefreshTokens" USING btree ("UserId");


--
-- Name: IX_SurveyAnswers_PostId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_SurveyAnswers_PostId" ON public."SurveyAnswers" USING btree ("PostId");


--
-- Name: IX_SurveyAnswers_StudentId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_SurveyAnswers_StudentId" ON public."SurveyAnswers" USING btree ("StudentId");


--
-- Name: IX_SurveyAnswers_SurveyOptionId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_SurveyAnswers_SurveyOptionId" ON public."SurveyAnswers" USING btree ("SurveyOptionId");


--
-- Name: IX_SurveyOptions_PostId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_SurveyOptions_PostId" ON public."SurveyOptions" USING btree ("PostId");


--
-- Name: IX_TaskAnswers_AdditionalMaterialId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_TaskAnswers_AdditionalMaterialId" ON public."TaskAnswers" USING btree ("AdditionalMaterialId");


--
-- Name: IX_TaskAnswers_StudentId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_TaskAnswers_StudentId" ON public."TaskAnswers" USING btree ("StudentId");


--
-- Name: IX_TaskAnswers_TaskId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_TaskAnswers_TaskId" ON public."TaskAnswers" USING btree ("TaskId");


--
-- Name: IX_Tasks_CourseId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Tasks_CourseId" ON public."Tasks" USING btree ("CourseId");


--
-- Name: IX_Tasks_PostId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Tasks_PostId" ON public."Tasks" USING btree ("PostId");


--
-- Name: IX_Tasks_StudentId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Tasks_StudentId" ON public."Tasks" USING btree ("StudentId");


--
-- Name: IX_Tasks_SubjectId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Tasks_SubjectId" ON public."Tasks" USING btree ("SubjectId");


--
-- Name: IX_Tasks_TeacherId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Tasks_TeacherId" ON public."Tasks" USING btree ("TeacherId");


--
-- Name: IX_Users_AuthorizationDataId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Users_AuthorizationDataId" ON public."Users" USING btree ("AuthorizationDataId");


--
-- Name: IX_Users_GroupId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Users_GroupId" ON public."Users" USING btree ("GroupId");


--
-- Name: IX_Users_PersonalDataId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Users_PersonalDataId" ON public."Users" USING btree ("PersonalDataId");


--
-- Name: AdditionalMaterials FK_AdditionalMaterials_Posts_PostId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AdditionalMaterials"
    ADD CONSTRAINT "FK_AdditionalMaterials_Posts_PostId" FOREIGN KEY ("PostId") REFERENCES public."Posts"("PostId") ON DELETE CASCADE;


--
-- Name: AdditionalMaterials FK_AdditionalMaterials_Users_UserId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AdditionalMaterials"
    ADD CONSTRAINT "FK_AdditionalMaterials_Users_UserId" FOREIGN KEY ("UserId") REFERENCES public."Users"("UserId") ON DELETE CASCADE;


--
-- Name: Comments FK_Comments_Posts_PostId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Comments"
    ADD CONSTRAINT "FK_Comments_Posts_PostId" FOREIGN KEY ("PostId") REFERENCES public."Posts"("PostId") ON DELETE CASCADE;


--
-- Name: Comments FK_Comments_Users_AuthorId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Comments"
    ADD CONSTRAINT "FK_Comments_Users_AuthorId" FOREIGN KEY ("AuthorId") REFERENCES public."Users"("UserId") ON DELETE CASCADE;


--
-- Name: CourseModelStudentModel FK_CourseModelStudentModel_Courses_CoursesCourseId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."CourseModelStudentModel"
    ADD CONSTRAINT "FK_CourseModelStudentModel_Courses_CoursesCourseId" FOREIGN KEY ("CoursesCourseId") REFERENCES public."Courses"("CourseId") ON DELETE CASCADE;


--
-- Name: CourseModelStudentModel FK_CourseModelStudentModel_Users_StudentsUserId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."CourseModelStudentModel"
    ADD CONSTRAINT "FK_CourseModelStudentModel_Users_StudentsUserId" FOREIGN KEY ("StudentsUserId") REFERENCES public."Users"("UserId") ON DELETE CASCADE;


--
-- Name: Courses FK_Courses_Groups_GroupId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Courses"
    ADD CONSTRAINT "FK_Courses_Groups_GroupId" FOREIGN KEY ("GroupId") REFERENCES public."Groups"("GroupId") ON DELETE CASCADE;


--
-- Name: Courses FK_Courses_Groups_GroupModelGroupId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Courses"
    ADD CONSTRAINT "FK_Courses_Groups_GroupModelGroupId" FOREIGN KEY ("GroupModelGroupId") REFERENCES public."Groups"("GroupId");


--
-- Name: Courses FK_Courses_Subjects_SubjectId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Courses"
    ADD CONSTRAINT "FK_Courses_Subjects_SubjectId" FOREIGN KEY ("SubjectId") REFERENCES public."Subjects"("SubjectId") ON DELETE CASCADE;


--
-- Name: Courses FK_Courses_Subjects_SubjectModelSubjectId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Courses"
    ADD CONSTRAINT "FK_Courses_Subjects_SubjectModelSubjectId" FOREIGN KEY ("SubjectModelSubjectId") REFERENCES public."Subjects"("SubjectId");


--
-- Name: Courses FK_Courses_Users_TeacherId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Courses"
    ADD CONSTRAINT "FK_Courses_Users_TeacherId" FOREIGN KEY ("TeacherId") REFERENCES public."Users"("UserId") ON DELETE CASCADE;


--
-- Name: Courses FK_Courses_Users_TeacherModelUserId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Courses"
    ADD CONSTRAINT "FK_Courses_Users_TeacherModelUserId" FOREIGN KEY ("TeacherModelUserId") REFERENCES public."Users"("UserId");


--
-- Name: LessonSupressedRequests FK_LessonSupressedRequests_Groups_GroupId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."LessonSupressedRequests"
    ADD CONSTRAINT "FK_LessonSupressedRequests_Groups_GroupId" FOREIGN KEY ("GroupId") REFERENCES public."Groups"("GroupId") ON DELETE CASCADE;


--
-- Name: LessonSupressedRequests FK_LessonSupressedRequests_LessonSlots_LessonSlotId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."LessonSupressedRequests"
    ADD CONSTRAINT "FK_LessonSupressedRequests_LessonSlots_LessonSlotId" FOREIGN KEY ("LessonSlotId") REFERENCES public."LessonSlots"("LessonSlotId") ON DELETE CASCADE;


--
-- Name: LessonSupressedRequests FK_LessonSupressedRequests_Lessons_AffectedLessonId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."LessonSupressedRequests"
    ADD CONSTRAINT "FK_LessonSupressedRequests_Lessons_AffectedLessonId" FOREIGN KEY ("AffectedLessonId") REFERENCES public."Lessons"("LessonId") ON DELETE CASCADE;


--
-- Name: LessonSupressedRequests FK_LessonSupressedRequests_Subjects_SubjectId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."LessonSupressedRequests"
    ADD CONSTRAINT "FK_LessonSupressedRequests_Subjects_SubjectId" FOREIGN KEY ("SubjectId") REFERENCES public."Subjects"("SubjectId") ON DELETE CASCADE;


--
-- Name: LessonSupressedRequests FK_LessonSupressedRequests_Users_TeacherId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."LessonSupressedRequests"
    ADD CONSTRAINT "FK_LessonSupressedRequests_Users_TeacherId" FOREIGN KEY ("TeacherId") REFERENCES public."Users"("UserId") ON DELETE CASCADE;


--
-- Name: Lessons FK_Lessons_Groups_GroupId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Lessons"
    ADD CONSTRAINT "FK_Lessons_Groups_GroupId" FOREIGN KEY ("GroupId") REFERENCES public."Groups"("GroupId") ON DELETE RESTRICT;


--
-- Name: Lessons FK_Lessons_Housings_HousingId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Lessons"
    ADD CONSTRAINT "FK_Lessons_Housings_HousingId" FOREIGN KEY ("HousingId") REFERENCES public."Housings"("HousingId") ON DELETE RESTRICT;


--
-- Name: Lessons FK_Lessons_LessonSlots_LessonNumberId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Lessons"
    ADD CONSTRAINT "FK_Lessons_LessonSlots_LessonNumberId" FOREIGN KEY ("LessonNumberId") REFERENCES public."LessonSlots"("LessonSlotId") ON DELETE RESTRICT;


--
-- Name: Lessons FK_Lessons_Subjects_SubjectId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Lessons"
    ADD CONSTRAINT "FK_Lessons_Subjects_SubjectId" FOREIGN KEY ("SubjectId") REFERENCES public."Subjects"("SubjectId") ON DELETE RESTRICT;


--
-- Name: Lessons FK_Lessons_Users_TeacherId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Lessons"
    ADD CONSTRAINT "FK_Lessons_Users_TeacherId" FOREIGN KEY ("TeacherId") REFERENCES public."Users"("UserId") ON DELETE RESTRICT;


--
-- Name: PostThemes FK_PostThemes_Courses_CourseId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."PostThemes"
    ADD CONSTRAINT "FK_PostThemes_Courses_CourseId" FOREIGN KEY ("CourseId") REFERENCES public."Courses"("CourseId") ON DELETE CASCADE;


--
-- Name: Posts FK_Posts_Courses_CourseId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Posts"
    ADD CONSTRAINT "FK_Posts_Courses_CourseId" FOREIGN KEY ("CourseId") REFERENCES public."Courses"("CourseId") ON DELETE RESTRICT;


--
-- Name: Posts FK_Posts_PostThemes_PostThemeId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Posts"
    ADD CONSTRAINT "FK_Posts_PostThemes_PostThemeId" FOREIGN KEY ("PostThemeId") REFERENCES public."PostThemes"("PostThemeId") ON DELETE SET NULL;


--
-- Name: Posts FK_Posts_Users_AdministratorModelUserId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Posts"
    ADD CONSTRAINT "FK_Posts_Users_AdministratorModelUserId" FOREIGN KEY ("AdministratorModelUserId") REFERENCES public."Users"("UserId");


--
-- Name: Posts FK_Posts_Users_StudentModelUserId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Posts"
    ADD CONSTRAINT "FK_Posts_Users_StudentModelUserId" FOREIGN KEY ("StudentModelUserId") REFERENCES public."Users"("UserId");


--
-- Name: Posts FK_Posts_Users_UserId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Posts"
    ADD CONSTRAINT "FK_Posts_Users_UserId" FOREIGN KEY ("UserId") REFERENCES public."Users"("UserId") ON DELETE RESTRICT;


--
-- Name: RefreshTokens FK_RefreshTokens_Users_UserId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."RefreshTokens"
    ADD CONSTRAINT "FK_RefreshTokens_Users_UserId" FOREIGN KEY ("UserId") REFERENCES public."Users"("UserId") ON DELETE CASCADE;


--
-- Name: SurveyAnswers FK_SurveyAnswers_Posts_PostId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."SurveyAnswers"
    ADD CONSTRAINT "FK_SurveyAnswers_Posts_PostId" FOREIGN KEY ("PostId") REFERENCES public."Posts"("PostId") ON DELETE CASCADE;


--
-- Name: SurveyAnswers FK_SurveyAnswers_SurveyOptions_SurveyOptionId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."SurveyAnswers"
    ADD CONSTRAINT "FK_SurveyAnswers_SurveyOptions_SurveyOptionId" FOREIGN KEY ("SurveyOptionId") REFERENCES public."SurveyOptions"("SurveyOptionId") ON DELETE CASCADE;


--
-- Name: SurveyAnswers FK_SurveyAnswers_Users_StudentId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."SurveyAnswers"
    ADD CONSTRAINT "FK_SurveyAnswers_Users_StudentId" FOREIGN KEY ("StudentId") REFERENCES public."Users"("UserId") ON DELETE CASCADE;


--
-- Name: SurveyOptions FK_SurveyOptions_Posts_PostId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."SurveyOptions"
    ADD CONSTRAINT "FK_SurveyOptions_Posts_PostId" FOREIGN KEY ("PostId") REFERENCES public."Posts"("PostId") ON DELETE CASCADE;


--
-- Name: TaskAnswers FK_TaskAnswers_AdditionalMaterials_AdditionalMaterialId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."TaskAnswers"
    ADD CONSTRAINT "FK_TaskAnswers_AdditionalMaterials_AdditionalMaterialId" FOREIGN KEY ("AdditionalMaterialId") REFERENCES public."AdditionalMaterials"("AdditionalMaterialId") ON DELETE CASCADE;


--
-- Name: TaskAnswers FK_TaskAnswers_Tasks_TaskId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."TaskAnswers"
    ADD CONSTRAINT "FK_TaskAnswers_Tasks_TaskId" FOREIGN KEY ("TaskId") REFERENCES public."Tasks"("TaskId") ON DELETE CASCADE;


--
-- Name: TaskAnswers FK_TaskAnswers_Users_StudentId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."TaskAnswers"
    ADD CONSTRAINT "FK_TaskAnswers_Users_StudentId" FOREIGN KEY ("StudentId") REFERENCES public."Users"("UserId") ON DELETE CASCADE;


--
-- Name: Tasks FK_Tasks_Courses_CourseId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Tasks"
    ADD CONSTRAINT "FK_Tasks_Courses_CourseId" FOREIGN KEY ("CourseId") REFERENCES public."Courses"("CourseId") ON DELETE CASCADE;


--
-- Name: Tasks FK_Tasks_Posts_PostId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Tasks"
    ADD CONSTRAINT "FK_Tasks_Posts_PostId" FOREIGN KEY ("PostId") REFERENCES public."Posts"("PostId") ON DELETE CASCADE;


--
-- Name: Tasks FK_Tasks_Subjects_SubjectId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Tasks"
    ADD CONSTRAINT "FK_Tasks_Subjects_SubjectId" FOREIGN KEY ("SubjectId") REFERENCES public."Subjects"("SubjectId") ON DELETE CASCADE;


--
-- Name: Tasks FK_Tasks_Users_StudentId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Tasks"
    ADD CONSTRAINT "FK_Tasks_Users_StudentId" FOREIGN KEY ("StudentId") REFERENCES public."Users"("UserId") ON DELETE CASCADE;


--
-- Name: Tasks FK_Tasks_Users_TeacherId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Tasks"
    ADD CONSTRAINT "FK_Tasks_Users_TeacherId" FOREIGN KEY ("TeacherId") REFERENCES public."Users"("UserId") ON DELETE CASCADE;


--
-- Name: Users FK_Users_AuthorizationDatas_AuthorizationDataId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Users"
    ADD CONSTRAINT "FK_Users_AuthorizationDatas_AuthorizationDataId" FOREIGN KEY ("AuthorizationDataId") REFERENCES public."AuthorizationDatas"("AuthorizationDataId") ON DELETE CASCADE;


--
-- Name: Users FK_Users_Groups_GroupId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Users"
    ADD CONSTRAINT "FK_Users_Groups_GroupId" FOREIGN KEY ("GroupId") REFERENCES public."Groups"("GroupId");


--
-- Name: Users FK_Users_PersonalDatas_PersonalDataId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Users"
    ADD CONSTRAINT "FK_Users_PersonalDatas_PersonalDataId" FOREIGN KEY ("PersonalDataId") REFERENCES public."PersonalDatas"("PersonalDataId") ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--

