[agent]
    interval = "10s"
    round_interval = true
    metric_batch_size = 1000
    metric_buffer_limit = 10000
    collection_jitter = "0s"
    flush_interval = "10s"
    flush_jitter = "0s"
    precision = ""
    debug = false
    quiet = false
    logfile = ""

[[outputs.influxdb_v2]]
    urls = ["http://influxdb:8086"]

    ## API token for authentication.
    token = "HK5OMN3ru-Igq5lNBY4WAwahkMj_kXNdODsqg2dcDJXIRUjS2Tuq4ScmzRGL-1FJKLFaL7TYicXFkZcziusjVw=="

    ## Organization is the name of the organization you wish to write to; must exist.
    organization = "my-org"

    ## Destination bucket to write into.
    bucket = "my-bucket"

[[inputs.disk]]
  ignore_fs = ["tmpfs", "devtmpfs", "devfs", "iso9660", "overlay", "aufs", "squashfs"]