// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MptRoomAPI.Models;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MptRoomAPI.Migrations
{
    [DbContext(typeof(MptRoomDbContext))]
    [Migration("20250501180352_AddedIsRevokedToRefreshToken")]
    partial class AddedIsRevokedToRefreshToken
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CourseModelStudentModel", b =>
                {
                    b.Property<int>("CoursesCourseId")
                        .HasColumnType("integer");

                    b.Property<int>("StudentsUserId")
                        .HasColumnType("integer");

                    b.HasKey("CoursesCourseId", "StudentsUserId");

                    b.HasIndex("StudentsUserId");

                    b.ToTable("CourseModelStudentModel");
                });

            modelBuilder.Entity("MptRoomAPI.Models.AdditionalMaterialModel", b =>
                {
                    b.Property<int>("AdditionalMaterialId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AdditionalMaterialId"));

                    b.Property<int?>("TaskModelPostId")
                        .HasColumnType("integer");

                    b.Property<string>("UriAbsolutePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("AdditionalMaterialId");

                    b.HasIndex("TaskModelPostId");

                    b.HasIndex("UserId");

                    b.ToTable("AdditionalMaterials");
                });

            modelBuilder.Entity("MptRoomAPI.Models.AuthorizationDataModel", b =>
                {
                    b.Property<int>("AuthorizationDataId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AuthorizationDataId"));

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("AuthorizationDataId");

                    b.ToTable("AuthorizationDatas");
                });

            modelBuilder.Entity("MptRoomAPI.Models.Base.UserBase", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<int>("AuthorizationDataId")
                        .HasColumnType("integer");

                    b.Property<int>("PersonalDataId")
                        .HasColumnType("integer");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.HasKey("UserId");

                    b.HasIndex("AuthorizationDataId");

                    b.HasIndex("PersonalDataId");

                    b.ToTable("Users");

                    b.HasDiscriminator<string>("UserType").HasValue("User");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("MptRoomAPI.Models.CourseModel", b =>
                {
                    b.Property<int>("CourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CourseId"));

                    b.Property<int>("GroupId")
                        .HasColumnType("integer");

                    b.Property<int?>("GroupModelGroupId")
                        .HasColumnType("integer");

                    b.Property<int>("SubjectId")
                        .HasColumnType("integer");

                    b.Property<int?>("SubjectModelSubjectId")
                        .HasColumnType("integer");

                    b.Property<int>("TeacherId")
                        .HasColumnType("integer");

                    b.Property<int?>("TeacherModelUserId")
                        .HasColumnType("integer");

                    b.HasKey("CourseId");

                    b.HasIndex("GroupId");

                    b.HasIndex("GroupModelGroupId");

                    b.HasIndex("SubjectId");

                    b.HasIndex("SubjectModelSubjectId");

                    b.HasIndex("TeacherId");

                    b.HasIndex("TeacherModelUserId");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("MptRoomAPI.Models.GroupModel", b =>
                {
                    b.Property<int>("GroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("GroupId"));

                    b.Property<int>("CourseNumber")
                        .HasColumnType("integer");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("GroupId");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("MptRoomAPI.Models.HousingModel", b =>
                {
                    b.Property<int>("HousingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("HousingId"));

                    b.Property<string>("HousingAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HousingName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("HousingId");

                    b.ToTable("Housings");
                });

            modelBuilder.Entity("MptRoomAPI.Models.LessonModel", b =>
                {
                    b.Property<int>("LessonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LessonId"));

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("integer");

                    b.Property<int>("GroupId")
                        .HasColumnType("integer");

                    b.Property<int>("HousingId")
                        .HasColumnType("integer");

                    b.Property<int>("LessonNumberId")
                        .HasColumnType("integer");

                    b.Property<int>("SubjectId")
                        .HasColumnType("integer");

                    b.Property<int>("TeacherId")
                        .HasColumnType("integer");

                    b.Property<int>("WeekType")
                        .HasColumnType("integer");

                    b.HasKey("LessonId");

                    b.HasIndex("GroupId");

                    b.HasIndex("HousingId");

                    b.HasIndex("LessonNumberId");

                    b.HasIndex("SubjectId");

                    b.HasIndex("TeacherId");

                    b.ToTable("Lessons");
                });

            modelBuilder.Entity("MptRoomAPI.Models.LessonSlotModel", b =>
                {
                    b.Property<int>("LessonSlotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LessonSlotId"));

                    b.Property<TimeOnly>("LessonEnd")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly>("LessonStart")
                        .HasColumnType("time without time zone");

                    b.HasKey("LessonSlotId");

                    b.ToTable("LessonSlots");
                });

            modelBuilder.Entity("MptRoomAPI.Models.PersonalDataModel", b =>
                {
                    b.Property<int>("PersonalDataId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PersonalDataId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Patronymic")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("PersonalDataId");

                    b.ToTable("PersonalDatas");
                });

            modelBuilder.Entity("MptRoomAPI.Models.PostModel", b =>
                {
                    b.Property<int>("PostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PostId"));

                    b.Property<int?>("AdministratorModelUserId")
                        .HasColumnType("integer");

                    b.Property<int>("CourseId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PostDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PostThemeId")
                        .HasColumnType("integer");

                    b.Property<string>("PostTitle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PostType")
                        .HasColumnType("integer");

                    b.Property<int?>("StudentModelUserId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("PostId");

                    b.HasIndex("AdministratorModelUserId");

                    b.HasIndex("CourseId");

                    b.HasIndex("PostThemeId");

                    b.HasIndex("StudentModelUserId");

                    b.HasIndex("UserId");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("MptRoomAPI.Models.PostThemeModel", b =>
                {
                    b.Property<int>("PostThemeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PostThemeId"));

                    b.Property<string>("PostThemeText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("PostThemeId");

                    b.ToTable("PostThemes");
                });

            modelBuilder.Entity("MptRoomAPI.Models.RefreshTokenModel", b =>
                {
                    b.Property<int>("RefreshTokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RefreshTokenId"));

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("boolean");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("RefreshTokenId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("MptRoomAPI.Models.SubjectModel", b =>
                {
                    b.Property<int>("SubjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SubjectId"));

                    b.Property<string>("HexademicalColor")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("SubjectName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("SubjectId");

                    b.ToTable("Subjects");
                });

            modelBuilder.Entity("MptRoomAPI.Models.SurveyOptionModel", b =>
                {
                    b.Property<int>("SurveyOptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SurveyOptionId"));

                    b.Property<string>("OptionName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PostId")
                        .HasColumnType("integer");

                    b.HasKey("SurveyOptionId");

                    b.HasIndex("PostId");

                    b.ToTable("SurveyOptions");
                });

            modelBuilder.Entity("MptRoomAPI.Models.TaskAnswerModel", b =>
                {
                    b.Property<int>("TaskAnswerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TaskAnswerId"));

                    b.Property<int?>("AdditionalMaterialId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("AssignmentTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PostId")
                        .HasColumnType("integer");

                    b.Property<int?>("PostModelPostId")
                        .HasColumnType("integer");

                    b.Property<int>("StudentId")
                        .HasColumnType("integer");

                    b.HasKey("TaskAnswerId");

                    b.HasIndex("AdditionalMaterialId");

                    b.HasIndex("PostId");

                    b.HasIndex("PostModelPostId");

                    b.HasIndex("StudentId");

                    b.ToTable("TaskAnswers");
                });

            modelBuilder.Entity("MptRoomAPI.Models.TaskModel", b =>
                {
                    b.Property<int>("PostId")
                        .HasColumnType("integer");

                    b.Property<int>("CourseId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DueTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Mark")
                        .HasColumnType("integer");

                    b.Property<int>("MaxMark")
                        .HasColumnType("integer");

                    b.Property<int>("StudentId")
                        .HasColumnType("integer");

                    b.Property<int>("SubjectId")
                        .HasColumnType("integer");

                    b.Property<int>("TaskStatusEnum")
                        .HasColumnType("integer");

                    b.Property<int>("TeacherId")
                        .HasColumnType("integer");

                    b.HasKey("PostId");

                    b.HasIndex("CourseId");

                    b.HasIndex("StudentId");

                    b.HasIndex("SubjectId");

                    b.HasIndex("TeacherId")
                        .IsUnique();

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("MptRoomAPI.Models.AdministratorModel", b =>
                {
                    b.HasBaseType("MptRoomAPI.Models.Base.UserBase");

                    b.HasDiscriminator().HasValue("Administrator");
                });

            modelBuilder.Entity("MptRoomAPI.Models.StudentModel", b =>
                {
                    b.HasBaseType("MptRoomAPI.Models.Base.UserBase");

                    b.Property<int?>("GroupId")
                        .HasColumnType("integer");

                    b.HasIndex("GroupId");

                    b.HasDiscriminator().HasValue("Student");
                });

            modelBuilder.Entity("MptRoomAPI.Models.TeacherModel", b =>
                {
                    b.HasBaseType("MptRoomAPI.Models.Base.UserBase");

                    b.HasDiscriminator().HasValue("Teacher");
                });

            modelBuilder.Entity("CourseModelStudentModel", b =>
                {
                    b.HasOne("MptRoomAPI.Models.CourseModel", null)
                        .WithMany()
                        .HasForeignKey("CoursesCourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MptRoomAPI.Models.StudentModel", null)
                        .WithMany()
                        .HasForeignKey("StudentsUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MptRoomAPI.Models.AdditionalMaterialModel", b =>
                {
                    b.HasOne("MptRoomAPI.Models.TaskModel", null)
                        .WithMany("Materials")
                        .HasForeignKey("TaskModelPostId");

                    b.HasOne("MptRoomAPI.Models.Base.UserBase", "User")
                        .WithMany("Materials")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MptRoomAPI.Models.Base.UserBase", b =>
                {
                    b.HasOne("MptRoomAPI.Models.AuthorizationDataModel", "AuthorizationData")
                        .WithMany()
                        .HasForeignKey("AuthorizationDataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MptRoomAPI.Models.PersonalDataModel", "PersonalData")
                        .WithMany()
                        .HasForeignKey("PersonalDataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AuthorizationData");

                    b.Navigation("PersonalData");
                });

            modelBuilder.Entity("MptRoomAPI.Models.CourseModel", b =>
                {
                    b.HasOne("MptRoomAPI.Models.GroupModel", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MptRoomAPI.Models.GroupModel", null)
                        .WithMany("Courses")
                        .HasForeignKey("GroupModelGroupId");

                    b.HasOne("MptRoomAPI.Models.SubjectModel", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MptRoomAPI.Models.SubjectModel", null)
                        .WithMany("Courses")
                        .HasForeignKey("SubjectModelSubjectId");

                    b.HasOne("MptRoomAPI.Models.TeacherModel", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MptRoomAPI.Models.TeacherModel", null)
                        .WithMany("Courses")
                        .HasForeignKey("TeacherModelUserId");

                    b.Navigation("Group");

                    b.Navigation("Subject");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("MptRoomAPI.Models.LessonModel", b =>
                {
                    b.HasOne("MptRoomAPI.Models.GroupModel", "Group")
                        .WithMany("Lessons")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MptRoomAPI.Models.HousingModel", "Housing")
                        .WithMany("Lessons")
                        .HasForeignKey("HousingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MptRoomAPI.Models.LessonSlotModel", "LessonNumber")
                        .WithMany()
                        .HasForeignKey("LessonNumberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MptRoomAPI.Models.SubjectModel", "Subject")
                        .WithMany("Lessons")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MptRoomAPI.Models.TeacherModel", "Teacher")
                        .WithMany("Lessons")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("Housing");

                    b.Navigation("LessonNumber");

                    b.Navigation("Subject");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("MptRoomAPI.Models.PostModel", b =>
                {
                    b.HasOne("MptRoomAPI.Models.AdministratorModel", null)
                        .WithMany("Posts")
                        .HasForeignKey("AdministratorModelUserId");

                    b.HasOne("MptRoomAPI.Models.CourseModel", "Course")
                        .WithMany("Posts")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MptRoomAPI.Models.PostThemeModel", "PostTheme")
                        .WithMany("Posts")
                        .HasForeignKey("PostThemeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MptRoomAPI.Models.StudentModel", null)
                        .WithMany("Posts")
                        .HasForeignKey("StudentModelUserId");

                    b.HasOne("MptRoomAPI.Models.TeacherModel", "Teacher")
                        .WithMany("Posts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("PostTheme");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("MptRoomAPI.Models.RefreshTokenModel", b =>
                {
                    b.HasOne("MptRoomAPI.Models.Base.UserBase", "User")
                        .WithOne("RefreshToken")
                        .HasForeignKey("MptRoomAPI.Models.RefreshTokenModel", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MptRoomAPI.Models.SurveyOptionModel", b =>
                {
                    b.HasOne("MptRoomAPI.Models.PostModel", "Post")
                        .WithMany()
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");
                });

            modelBuilder.Entity("MptRoomAPI.Models.TaskAnswerModel", b =>
                {
                    b.HasOne("MptRoomAPI.Models.AdditionalMaterialModel", "AdditionalMaterial")
                        .WithMany()
                        .HasForeignKey("AdditionalMaterialId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MptRoomAPI.Models.PostModel", "Post")
                        .WithMany()
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MptRoomAPI.Models.PostModel", null)
                        .WithMany("TaskAnswers")
                        .HasForeignKey("PostModelPostId");

                    b.HasOne("MptRoomAPI.Models.StudentModel", "Student")
                        .WithMany("TaskAnswers")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AdditionalMaterial");

                    b.Navigation("Post");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("MptRoomAPI.Models.TaskModel", b =>
                {
                    b.HasOne("MptRoomAPI.Models.CourseModel", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MptRoomAPI.Models.PostModel", "Post")
                        .WithOne()
                        .HasForeignKey("MptRoomAPI.Models.TaskModel", "PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MptRoomAPI.Models.StudentModel", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MptRoomAPI.Models.SubjectModel", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MptRoomAPI.Models.TeacherModel", "Teacher")
                        .WithOne()
                        .HasForeignKey("MptRoomAPI.Models.TaskModel", "TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Post");

                    b.Navigation("Student");

                    b.Navigation("Subject");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("MptRoomAPI.Models.StudentModel", b =>
                {
                    b.HasOne("MptRoomAPI.Models.GroupModel", "Group")
                        .WithMany("Students")
                        .HasForeignKey("GroupId");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("MptRoomAPI.Models.Base.UserBase", b =>
                {
                    b.Navigation("Materials");

                    b.Navigation("RefreshToken")
                        .IsRequired();
                });

            modelBuilder.Entity("MptRoomAPI.Models.CourseModel", b =>
                {
                    b.Navigation("Posts");
                });

            modelBuilder.Entity("MptRoomAPI.Models.GroupModel", b =>
                {
                    b.Navigation("Courses");

                    b.Navigation("Lessons");

                    b.Navigation("Students");
                });

            modelBuilder.Entity("MptRoomAPI.Models.HousingModel", b =>
                {
                    b.Navigation("Lessons");
                });

            modelBuilder.Entity("MptRoomAPI.Models.PostModel", b =>
                {
                    b.Navigation("TaskAnswers");
                });

            modelBuilder.Entity("MptRoomAPI.Models.PostThemeModel", b =>
                {
                    b.Navigation("Posts");
                });

            modelBuilder.Entity("MptRoomAPI.Models.SubjectModel", b =>
                {
                    b.Navigation("Courses");

                    b.Navigation("Lessons");
                });

            modelBuilder.Entity("MptRoomAPI.Models.TaskModel", b =>
                {
                    b.Navigation("Materials");
                });

            modelBuilder.Entity("MptRoomAPI.Models.AdministratorModel", b =>
                {
                    b.Navigation("Posts");
                });

            modelBuilder.Entity("MptRoomAPI.Models.StudentModel", b =>
                {
                    b.Navigation("Posts");

                    b.Navigation("TaskAnswers");
                });

            modelBuilder.Entity("MptRoomAPI.Models.TeacherModel", b =>
                {
                    b.Navigation("Courses");

                    b.Navigation("Lessons");

                    b.Navigation("Posts");
                });
#pragma warning restore 612, 618
        }
    }
}
