using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using MptRoomAPI.DTO;
using MptRoomAPI.Models;

namespace MptRoomAPI.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    public class SubjectController : ControllerBase
    {
        private readonly MptRoomDbContext _context;
        private readonly ILogger<SubjectController> _logger;

        public SubjectController(MptRoomDbContext context, ILogger<SubjectController> logger)
        {
            _context = context;
            _logger = logger;
        }

        // GET: api/Subject
        [HttpGet]
        [Authorize]
        public async Task<ActionResult<IEnumerable<SubjectDTO>>> GetSubjects()
        {
            try
            {
                var subjects = await _context.Subjects
                    .Select(s => new SubjectDTO
                    {
                        SubjectId = s.SubjectId,
                        SubjectName = s.SubjectName,
                        HexademicalColor = s.HexademicalColor
                    })
                    .ToListAsync();

                return Ok(subjects);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error retrieving subject records.");
                return StatusCode(500, "An error occurred while retrieving subject records.");
            }
        }

        // GET: api/Subject/5
        [HttpGet("{id}")]
        [Authorize]
        public async Task<ActionResult<SubjectDTO>> GetSubjectModel(int id)
        {
            try
            {
                var subject = await _context.Subjects
                    .Where(s => s.SubjectId == id)
                    .Select(s => new SubjectDTO
                    {
                        SubjectId = s.SubjectId,
                        SubjectName = s.SubjectName,
                        HexademicalColor = s.HexademicalColor
                    })
                    .FirstOrDefaultAsync();

                if (subject == null)
                {
                    return NotFound($"Subject with ID {id} not found.");
                }

                return Ok(subject);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, $"Error retrieving subject with ID {id}.");
                return StatusCode(500, "An error occurred while retrieving the subject record.");
            }
        }

        // PUT: api/Subject/5
        [HttpPut("{id}")]
        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> PutSubjectModel(int id, SubjectDTO subjectDTO)
        {
            if (id != subjectDTO.SubjectId)
            {
                return BadRequest("Subject ID mismatch.");
            }

            try
            {
                var subject = await _context.Subjects.FindAsync(id);

                if (subject == null)
                {
                    return NotFound($"Subject with ID {id} not found.");
                }

                subject.SubjectName = subjectDTO.SubjectName;

                _context.Entry(subject).State = EntityState.Modified;

                await _context.SaveChangesAsync();

                return NoContent();
            }
            catch (DbUpdateConcurrencyException ex)
            {
                _logger.LogError(ex, "Concurrency error while updating subject record.");
                return StatusCode(500, "An error occurred while updating the subject record.");
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Unexpected error while updating subject record.");
                return StatusCode(500, "An error occurred while updating the subject record.");
            }
        }

        // POST: api/Subject
        [HttpPost]
        [Authorize(Roles = "Administrator")]
        public async Task<ActionResult<SubjectDTO>> PostSubjectModel(SubjectDTO subjectDTO)
        {
            try
            {
                var subject = new SubjectModel
                {
                    SubjectName = subjectDTO.SubjectName,
                    HexademicalColor = subjectDTO.HexademicalColor,
                };

                _context.Subjects.Add(subject);
                await _context.SaveChangesAsync();

                subjectDTO.SubjectId = subject.SubjectId;  // Assuming SubjectId is autogenerated

                return CreatedAtAction(nameof(GetSubjectModel), new { id = subjectDTO.SubjectId }, subjectDTO);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error while creating subject record.");
                return StatusCode(500, "An error occurred while creating the subject record.");
            }
        }

        // DELETE: api/Subject/5
        [HttpDelete("{id}")]
        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> DeleteSubjectModel(int id)
        {
            try
            {
                var subject = await _context.Subjects.FindAsync(id);
                if (subject == null)
                {
                    return NotFound($"Subject with ID {id} not found.");
                }

                _context.Subjects.Remove(subject);
                await _context.SaveChangesAsync();

                return NoContent();
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error while deleting subject record.");
                return StatusCode(500, "An error occurred while deleting the subject record.");
            }
        }

        private bool SubjectModelExists(int id)
        {
            return _context.Subjects.Any(e => e.SubjectId == id);
        }
    }
}
